### ISSUE TITLE
 https://home.dynamics.com is a broken link

### ISSUE THREAD

**Issue by AtallahM** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#10]
# Module: 1
#### Step: 00

Description of issue
 https://home.dynamics.com is a broken link
Repro steps:
navigate to  https://home.dynamics.com
We get 
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
What is the alternative path for the lab

**Comment by CeleneA** [comment]
The lab has been updated.  The link to be accessed (once logged in) is https://www.office.com/apps.
