### ISSUE TITLE
Field Service labs - missing instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#14]
# Module: 05
#### Step: 03

# Module: 05
#### Step: 04

Description of issue
* No mention of which work order type to fill in. Only mention of primary incident type in the steps. Should the reference to "primary incident type" actually be "work order type"? 

Additional errors in 5.2 
* step 6 - need to tell delegates to select the newly created work order in the view, so that the book button appears.
* step 7 - i don't have a record for Ryan Brim to select him as the resource.. instead i took Christa Geller, but people can also book against any contact they have created themselves.
* step 13 - tell people of "unscheduled work orders" does not appear on the bottom of the screen, they need to click on "new schedule board - on" (top right hand side of the screen).
* step 16 - i have no resources available for this requirement - need to adjust the filters... please advise which necessary adjustments to make so that resources appear for selection.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review solved Step 4 with pull request #21. MOC Labs Review confirms other issues.

**Comment by CeleneA** [comment]
Just published updated lab steps. Thank you for bringing to my attention.

**Comment by chaast** [comment]
thank you very much Celene. great to hear
