### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by jleblancxaf** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#15]
Description of issue
Despite no articles being shown, the instructions just have you view existing articles, but dont actually have you interact with any of them. the following steps show how to create a new one, and the lab can still be completed

**Comment by jleblancxaf** [comment]
The first page of instructions tell you to click on Powerapps for marketing, but Powerapps for Operations is the only powerapps listed in the menu.

**Comment by CeleneA** [comment]
jleblancxaf
I am just testing to validate your issues.
You need to open the environment (and it is no longer named WWLLABnnn, so I will get that fixed). Once you open the environment, you should have all the apps available to you.
![image](https://user-images.githubusercontent.com/50712180/193616537-143a99cf-a771-4fdd-bc13-2f8b1bbd5e45.png)

In terms of the other issue, I have updated the verbiage in the Knowledge Article lab to reflect your feedback.
