### ISSUE TITLE
Out of sequence content in Module 5

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#22]
# Module: 5
Hello, 
I have noticed that Mod 5, part 2 contains the instruction as "Module 4, lab 4.2". 
Can you please confirm if this is intentional or a mistake? 

Thanks!

**Comment by CeleneA** [comment]
This has just been fixed. Thank you for pointing this out.
