### ISSUE TITLE
GitHub Pages missing

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#25]
The GitHub pages for MB-910 i.e., user-friendly lab instructions is not linked on the main repo page under about 
Please add https://microsoftlearning.github.io/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/

**Comment by CeleneA** [comment]
done.
