### ISSUE TITLE
Title of demo 

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#27]
# Module: 5
## Demo: 3

The demo DEMO[MB-910]_M05_D5.3_Asset_Management_and_Connected_Field_Service.md is for the Field Service module not Customer Service. Need to change the module name at the top of the file

**Comment by CeleneA** [comment]
Thank you for putting your eagle eye to work - I appreciate it that you raise issues. 
Fix has been made.
