### ISSUE TITLE
Lab 5.1 and 5.2 in MD format 

### ISSUE THREAD

**Issue by QAJaneHowell** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#3]
# Module: 05
#### Step: all

Description of issue
This lab, along with lab 5.2, is only available in the MD format. This means that some of the instructions are not visible on the page as the format is wider than the screen size. 
Please re-format these two labs as per the other labs.  

Repro steps:

1.
1.
1.

**Comment by CeleneA** [comment]
This should be fixed now

**Comment by CeleneA** [comment]
fixed
