### ISSUE TITLE
Only one student can go live on marketing email

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#30]
# Module: 2
#### Step: 4

Description of issue

The environment is shared and there is only one marketing email titled Introduction to Chairs

Students should clock Save as to create a copy of the marketing email with their initials and then View record and then Go Live

**Comment by ephiax20** [comment]
Given the rest of the module; I don't think it's necessary for each student to use a unique Marketing Email. They are creating a unique Customer Journey (for their own Segment of Contacts) and there's no issue with multiple Journeys using the same email template.  I've updated wording on Step 4 to reflect this, if it's already Live, skip to the next step.

**Comment by julians1966** [comment]
The problem is that only one of the students can Go Live (the first one to reach that step) and the others are confused or get an error

**Comment by ephiax20** [comment]
I've updated wording on Step 4 to reflect this, if it's already Live, skip to the next step.

**Comment by CeleneA** [comment]
fixed
