### ISSUE TITLE
Lead and Company names need initials appended

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#31]
# Module: 3
#### Step: 4

Description of issue

When running the course, students will get different experience if they are not the first to qualify the lead. 
Last name, company name, phone number, and email addresses should be unique for each student otherwise the duplicate detection is triggered and a Matched account and a Matched contact is displayed

![Matched Account and Contact](https://user-images.githubusercontent.com/29278645/199748748-1cc05957-8cf4-4470-ba3e-d25e259cc73c.png)

**Comment by ephiax20** [comment]
Fixed in latest commit.

**Comment by CeleneA** [comment]
fixed
