### ISSUE TITLE
Competitor name need initials appended

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#32]
# Module: 3
#### Step: 17

Description of issue

Competitor names need to be unique as otherwise will have multiple competitors with the same name

![Multiple Competitors](https://user-images.githubusercontent.com/29278645/199750934-9db9e277-e3aa-44b4-a9e5-1eb29b4a2b8a.png)
.

**Comment by ephiax20** [comment]
Fixed.

**Comment by CeleneA** [comment]
fixed
