### ISSUE TITLE
Publish pane on knowledge articles appears automatically when click on Finish in the Business Process Flow 

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#33]
# Module: 4
#### Step: 13

Description of issue

When you click on the Finish button on the Publish stage in the business process flow, the Publish pane opens automatically so step 13 is unecessary

**Comment by ephiax20** [comment]
![image](https://user-images.githubusercontent.com/116392278/199950856-ebcff832-1b67-4d38-b444-52b9b91e7b21.png)

Not Step 13, I believe this is required.

Publishing is around Step 28, I've updated this too.
