### ISSUE TITLE
Knowledge articles can take several minutes to be available in cases

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#34]
# Module: 4
#### Step: 16

Description of issue

The knowledge article created in Lab 4.1 takes several minutes to appear in the knowledge search

**Comment by ephiax20** [comment]
I'll add this as a Note, after the Publish step.

**Comment by CeleneA** [comment]
fixed
