### ISSUE TITLE
Lab 4.1 - create and manage cases in D365 customer service - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#42]
# Module: 4
#### Step:1

Description of issue
the student should not open D365 customer service workspace to get to the case records, but instead should open customer service hub.

#### Step: 6

Description of issue
contact record for patrick sands does not exist.

#### Step:16

Description of issue
we did not create a knowledge article in earlier labs. there are no knowledge article results found.

**Comment by ephiax20** [comment]
RE: Task 1, Step 1 - Either model-driven application allows access to Cases.  I don't see any reason to choose one over the other.

Step 6, I'm seeking clarification on this data issue, however as workaround any Contact record will do for the purposes of this Lab.

Step 16, I'm seeking clarification on this issue too.

**Comment by chaast** [comment]
hi ephiax, thank you for getting in touch. 

please notice this screenshot here ref. the customer service workspace. as you can see, in the labs, this app does not show the option to select Cases from the site map on the left side of the screen.

![image](https://user-images.githubusercontent.com/89986870/229736933-ddbe95a7-cf0d-451c-844b-ce1132eee787.png)

**Comment by chaast** [comment]
also - when you say, you are seeking clarification - you mean from me? if so, what do you need from me?

I appreciate we can take another contact from the list, but nevertheless, the instructions are confusing for learners. Learners should be able to follow lab instructions without confusion - this impacts their course experience!

**Comment by ephiax20** [comment]
Hi chaast, thanks. I am seeking clarification on these points from the Content Owner.

I see there is an issue with the Site Map / Navigation missing from that Customer Service workspace application in your screenshot.

**Comment by CeleneA** [comment]
This lab has been updated
