### ISSUE TITLE
Lab 5.1 explore d365 field service - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#43]
# Module: 05
#### Step: 10

Description of issue
when completing the work order details, please note you need values for all mandatory fields. 
Also the field Taxable is not visible in the form.

#### Step: 17

Description of issue
default work order type must be set on the incident type before you can convert to a work order.

#### Step: 19 &20
Description of issue
the inspect system health and inspect range of motion services were not added to the work order -- i suspect the required records were not fully set up for this lab  to show the requested result (there are no work order services or tasks in the system).

**Comment by ephiax20** [comment]
Unable to replicate past Step 6, "Incident Type" is not available.

![image](https://user-images.githubusercontent.com/116392278/230060621-4d0b6651-08a0-4602-aa11-25238f88e234.png)

**Comment by chaast** [comment]
that's correct.  I created a record from scratch for "unit overheating"? but did not know which parameters to set when creating the record -- that's probably why we are getting errors later in the lab.

thank  you for confirming Ephiax20.

This potentially requires a pull request maybe?

**Comment by CeleneA** [comment]
chaast - did you follow the instructions in the TrainerPrepGuide?
Setup Requirements for Field Service Module
1.	Make Sure that all Users have the Field Service App Access Security Role.  
2.	Deploy Field Service Demo Data
a.	Locate the FS_Demo_Data.zip file available in the class resources.  
b.	Right click the FS_Demo_Data.zip file, and choose Unblock (It may not be there and that is OK)

**Comment by chaast** [comment]
hi Celene, thank you for your comment.

These instructions should be part of the lab set up... or at least part of the set up for the lab provider.... as instructors we are literally running from course to course, and are therefore time limited to consult different sources of information.

**Comment by CeleneA** [comment]
Chaast - the lab has been updated and now also includes a link to the demo data.

**Comment by chaast** [comment]
Hi Celene, many thanks for coming back to me so quickly. 

My team is contacting Skillable to see if they can update the live class link which has already been opened so i can test the link on Friday and report back to you.

**Comment by CeleneA** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chaast** [comment]
![image](https://user-images.githubusercontent.com/89986870/233652288-31587205-38d9-495e-99b3-20222e68a009.png)

Hi Celene, i have just tried to upload the data.. followed the instructions to the letter, but this is the error i received.... so sadly the link to the sample data  did not work correctly for me

**Comment by CeleneA** [comment]
Hi Chaast -
thank you for your patience with us. I have made another update to the Trainer Prep Guide, which is to follow the manual demo data upload steps. 
1. demo data is here: https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/tree/master/Instructions/Labs 
![image](https://user-images.githubusercontent.com/50712180/233800812-c7a59e1a-269d-4d94-aac9-794e52699a4e.png)

In terms of demo data upload, please follow the manual upload steps.

Updated Trainer Prep Guide should be live on Monday. in the meantime:
### Setup Requirements for Field Service Module

 

It is important that you walk through the installation of the Field Service demo data. Without the demo data installed, you will struggle to effectively demonstrate the application. More importantly, the field service lab will not work for the students. The demo data includes multiple items that are referenced in the lab. 

 

**Task 1: Add products to the Product Catalog**

You are going to create two products. These products will be added to an incident type that students will select when they are creating work orders in the exercise. 

1. Using the navigation on the left, change the Area from **Service** to **Settings**. 

2. Under the General group, select **Products**. 

3. Select the **Add Product** button. 

4. Configure the Product as follows:

	- **Name:** Inspect Health System

	- **Product ID:** INS-HEALTH-1234

	- **Unit Group:** Default Unit

	- **Default Unit:** Primary Unit

	- **Decimals Supported:** 2

5. Select the **Field Service** tab. 

6. Set the **Field Service Product Type** field to **Service.**

7. Select the **Save** button to save the record and leave it open. 

8. Select the **Publish** button and select the **Confirm** button. 

9. Select the **Save and Close** button to exit the product. 

10. Select the **Add Product** button again. 

11. Configure the Product as follows:

	- **Name:** Inspect Range of Motion

	- **Product ID:** INS-RANGE-1234

	- **Unit Group:** Default Unit

	- **Default Unit:** Primary Unit

	- **Decimals Supported:** 2

12. Select the **Field Service** tab. 

13. Set the **Field Service Product Type** field to **Service.**

14. Select the **Save** button to save the record and leave it open. 

15. Select the **Publish** button and select the **Confirm** button. 

16. Select the **Save and Close** button to exit the product. 

 

**Task 2: Create a Price List and add products to it**

Now that your products are created, you are going to create a US Bill Rates price list and add the products as price list items. 

 

1. While still in the **Settings** area of the application, select **Price Lists**. 

2. On the Command bar, select the **New** button. 

3. Set the **Price List** **Name** to **US Bill Rates.**

4. Select the **Save** button to save the record and leave it open. 

5. Select the **Price List Items** tab. 

6. Select the **New Price List Item** button. 

7. Configure the Price List Item as follows:

	- **Price List:** US Bill Rates

	- **Product:** Inspect Health System

	- **Unit:** Primary Unit

8. Select the **Pricing Information** tab. 

9. Leave the **Pricing Method** at **Currency Amount**.

10. Set the **Amount** field to **$150.00.**

11. Select the **Save and Close** button.

12. Select the **New Price List Item** button again. 

13. Configure the Price List Item as follows:

	- **Price List:** US Bill Rates

	- **Product:** Inspect Range of Motion

	- **Unit:** Primary Unit

14. Select the **Pricing Information** tab. 

15. Leave the **Pricing Method** at **Currency Amount**.

16. Set the **Amount** field to **$100.00.**

17. Select the **Save and Close** button.

 

**Task 3: Create Work Order Types**

Work order types are used to identify the type of work being done on the work order. We will be associating the Work order type with an Incident type we will be creating in the next task. 

1. Using the navigation on the left, select **Work Order Types**. 

2. On the **Command Bar**, select the **New** button. 

3. In the **Name** field, enter **Service Call**. 

4. Set the **Price List** to **US Bill Rates**. 

5. Select the **Save and Close** button. 

 

**Task 4: Create a Territory**

1. Using the navigation on the left, select **Territories**. 

2. On the **Command Bar**, select the **New** button. 

3. In the **Territory Name** field, enter **WA**. 

4. Select the **Save and Close** button. 

 

 

**Task 5: Create Incident Types**

Incident Types are used to populate information onto work orders when they are created. In this task we will be creating two incident types, Unit Overheating, and Line Connection Lost. We will be populating items to the Unit Overheating Incident type. We will not be adding items to Line Connection Lost incident type, but you are welcome to do so later if you would like. 

1. Using the navigation on the left select **Incident Types**. 

2. On the **Command Bar**, select the **New** button. 

3. In the **Name** field, enter **Unit Overheating**.

4. Select the **Details** tab. 

5. Set the **Default Work Order** type to **Service Call**. 

6. Select the **Save** button to save the record and leave it open. 

7. Select the **Services** tab. 

8. Select the **New Incident Type Service** button. 

9. Configure as follows:

	- **Name:** Inspect Health System

	- **Service:** Inspect Health System

	- **Unit:** Primary Unit

	- **Incident Type:** Unit Overheating

	- **Duration:** 45 Minutes

10. Select the **Save and Create New** button. 

11. Configure as follows:

	- **Name:** Inspect Range of Motion

	- **Service:** Inspect Range of Motion

	- **Unit:** Primary Unit

	- **Incident Type:** Unit Overheating

	- **Duration:** 1 hour

12. Select the **Save and Close** button. 

13. Select the **Service Tasks** tab. 

14. Select the **New Incident Type Service Task** button. 

15. Set the **Name** field to **Inspect Unit**. 

16. In the **Task Type** field, select **New Service Task Type.**

17. Configure as follows:

	- **Name:** Inspect Unit.

	- **Duration:** 1 hour

18. Select the **Save and Close** button. 

19. Make sure your **Incident Type Service Task** is as follows:

	- **Name:** Inspect Unit

	- **Task Type:** Inspect unit

	- **Estimated Duration:** 1 Hour

	- **Incident Type:** unit Overheating. 

20. Select the **Save and Close** button. 

21. On the **Unit Overheating** Incident Type, select the **Save and Close** button.

Next, we will create the Line Connection Lost Incident Type. If you want to add products, services, and tasks to it later you can. 

22. While on the **Active Incident Types** screen, select the **New** button again. 

23. In the **Name** field, enter **Line Connection Lost**.

24. Select the **Details** tab.

25. Set the **Default Work Order Type** to **Service Call**. 

26. Select the **Save and Close** button. 

You should now have all the supporting elements required for your students to leverage in class.

**Comment by chaast** [comment]
Hi Celene, very many thanks for this product update.

**Comment by CeleneA** [comment]
Chaast - are you satisfied with the resolution? Can I close the issue?

**Comment by chaast** [comment]
Hi Celene. Yes, thank you very much for all your help.

**Comment by CeleneA** [comment]
Chaast - thank you for your persistence!
