### ISSUE TITLE
LAb 1.1 create a simple customer journey -- incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#44]
# Module: 02
#### Step: 05

Description of issue
* Fargo customer segment does not exist -- the previous exercise that created this is no longer in the lab content.

#### Step: 07

Description of issue
*  the previous exercise that created the email is no longer in the lab content.

**Comment by ephiax20** [comment]
Hi chaast, the instructions have recently been refreshed and updated to create two Contacts with City attribute 'Fargo' and then create a Dynamic Segment based on this attribute.

**Comment by chaast** [comment]
that's great. many thanks Ephiax.

**Comment by CeleneA** [comment]
This lab has been updated
