### ISSUE TITLE
Lab 3.1 steps not accurate 

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#48]
Learning Path 3 - Module 1

Step 8 says to select Qualify but after this you are not able to complete step 9 and 10 as per the instructions. Selecting the drop down arrow next to the owner field does not show "Est. Close Date" or "Est Revenue".

Steps:

8. On the Command bar, select the Qualify button.
9. On the Opportunity Header at the top of the record, select the down arrow next to the Owner field.
10. Complete as follows:

- Est. Close Date: Two days from today
- Est Revenue: $50,000

**Comment by ephiax20** [comment]
@LewisGoDeploy do you have a screenshot of this?

I'm unable to reproduce.

![image](https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/assets/116392278/0311d7bf-45c4-4cc5-b501-cb6d0aceb7f9)

**Comment by LewisGoDeploy** [comment]
Your screenshot doesn't appear to be following the exact steps from lab 3.1: https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/blob/master/Instructions/Labs/LAB%5BMB-910%5D_LP03_M01_Lab1_Create_and_manage_an_Opportunity.md 

3.1 specifies that you need to create a Lead from the Sales Hub and then select Qualify. There is no Qualify button available to me unless I save the lead.

After saving the Lead and then clicking Qualify, step 8 specifies:
"The system will close the Lead record and create a new Opportunity record. Notice that the Lead to Opportunity business process flow has automatically been advanced to the Develop stage." - This does not happen for me, following these steps.

![image](https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/assets/114931569/947191e9-0010-4758-8266-7333c6c14f16)

**Comment by ephiax20** [comment]
I am getting an inconsistent behavior also on whether or not saving the record is required. It seems like the auto-save function should kicks in and save it, but not seeing it do that every time.   If the auto-save works it doesn't make sense to add a **Save** step to the instructions.

**Comment by ephiax20** [comment]
@LewisGoDeploy is a new Opportunity record actually being created, it just doesn't redirect you to it??

**Comment by LewisGoDeploy** [comment]
No - even when I save the Lead, it stays as "Lead" and does not automatically change to Opportunity.

**Comment by ephiax20** [comment]
In your screenshot the Lead is Qualified, so an Opportunity record should have been created. Do you see it when selecting **Opportunities** from the site navigation on the left side, as in my screenshot?

**Comment by ephiax20** [comment]
@LewisGoDeploy Please can you check this setting in your environment https://learn.microsoft.com/en-us/dynamics365/sales/define-lead-qualification-experience   It should be set to Yes?

![image](https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/assets/116392278/5ecdc7b5-c88e-4846-9f4c-286b2794dfd5)

**Comment by CeleneA** [comment]
@LewisGoDeploy - can you please review the fix proposed by @ephiax20 and see if it resolves the issue?

**Comment by ephiax20** [comment]
Hi @LewisGoDeploy have you had a chance to review this one??

**Comment by CeleneA** [comment]
@LewisGoDeploy - I am going to close this issue as we believe we have identified root cause and have not heard back from you in terms of having the issue recur.
