### ISSUE TITLE
In Microsoft365.com Apps front page neither the Business Apps group nor Sales Hub is not visible

### ISSUE THREAD

**Issue by fonsell** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#52]
# Module: 1
#### Step: 12

Even the admin of the tenant can do the lab without problems, the students with their standard users with their Sales Enterprise App access and System admin roles, cannot see Business Apps tab nor Sales Hub in www.microsoft365.com/apps

Repro steps:

1. use for example Alan Steiner user credentials - navigate to the url above - no Sales Hub visible there
1.
1.

**Comment by CeleneA** [comment]
Following up on this...

**Comment by CeleneA** [comment]
MB-910 labs are currently offline. Will address one tenant is back up and I can validate the issue still exists.

**Comment by CeleneA** [comment]
still waiting for tenant availability

**Comment by CeleneA** [comment]
I am going to close the issue as there are currently no tenants available and I cannot test. Please refile if the issue recurs once tenants are once more available
