### ISSUE TITLE
Lab 2.1 - Journey is missing necessary Segment and Email from the trainer prep guidance

### ISSUE THREAD

**Issue by fonsell** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#53]
# Module: Customer Insights
#### Step: 6 and 12

Trainer prep guide is missing the necessary preparation tasks to create Fargo Contacts -segment and Email (and publishing that email to be useful in the lab)

Also in step 13 - the Button says Publish and not Go live

Repro steps:

1.
1.
1.

**Comment by CeleneA** [comment]
Reviewing this bug.

**Comment by CeleneA** [comment]
the bug was caused by a change in data in the tenant. I have updated the Trainer Prep Guide and added Instructor Prep steps to add a segment and an email. The update will publish this Friday and should be available on Monday 27
