### ISSUE TITLE
FS_Demo_Data uses old XRM Tooling connections from 2017

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#6]
# Module: 00
### Task: 2

Description of issue

The FS_Demo_Data icnludes very old Package Deployer connection dlls 

The files in the FS_DemoData folder need to be replaced with the PackageDeployer files from the core Nuget tools https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools

**Comment by CeleneA** [comment]
this issue has now been resolved.  Demo data pack has been updated
