### ISSUE TITLE
DEMO[MB-910]_M04_D4.3_Asset_Management_and_Connected_Field_Service.md

### ISSUE THREAD

**Issue by LuongNguyen0906** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#7]
# Module: 04
#### Step: 00

Description of issue:
the below sentence clearly is missing some parts, it's not understandable as it is. 

"Customers often have physical assets that require work and maintenance to be performed. These assets are often installed initially typically will have preventative maintenance contracts opened against them Dynamics 365 Field Service Includes Asset Management functionality that works hand-in-hand with Connected Field Service Functionality"

**Comment by CeleneA** [comment]
fixed
