### ISSUE TITLE
Dynamics Interface Changes to Module 5

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#9]
# Module: 5: Learn the Fundamentals of Dynamics 365 Project Operations
## Lab/Demo: 53. Dynamics 365 Project Operations capstone lab
##Exercise 2: Manage a project
#### Step: 00

Description of issue

I believe the "schedule tab" has been replaced by the schedule board. This section may need rewritten. Previous parts of the series make use of the schedule board. I'm not sure why the lab is using the schedule tab still. It no longer exists.

![image](https://user-images.githubusercontent.com/47234227/129061020-3a6ff3bc-3554-490f-9556-66ae3117ddac.png)

**Comment by CeleneA** [comment]
Hi FireyJoe - thank you for your feedback.
I am about to launch a review and update of the content, so appreciate the comment and will integrate your feedback into the update.
